import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import TopBar from "@/components/TopBar/TopBar";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-gray-950 text-white`}>
          {children}
          <ToastContainer position="bottom-right" autoClose={8000} hideProgressBar={false} newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss draggable={false} pauseOnHover theme="dark" />
        </body>
      </html>
    </ClerkProvider>
  );
}
/*
const MenuItem = ({ name, link, icon, size, alt }) => {
  return (
    <Link href={link} className="flex justify-center p-2 hover:bg-blue-700 rounded group">
      <Image src={`/${icon}.svg`} width={size} height={size} alt={alt} />
    </Link>
  );
};


 <div className="flex h-screen">
            {user && user.publicMetadata.accepted && (
              <div className="px-3 flex-shrink-0 py-8 border-r border-gray-900 text-white sticky top-0 h-screen flex flex-col items-center gap-8 overflow-y-auto overflow-x-clip">
                <UserButton />
                <div className="flex flex-col gap-4">
                  <MenuItem name="Accounts" link="/profile" icon="profile" size="25" alt="profile-icon" />
                  <MenuItem name="Teams" link="/teams" icon="team" size="25" alt="teams-icon" />
                  <MenuItem name="Schedule" link="/" icon="calendar" size="25" alt="schedule-icon" />
                  {user.publicMetadata.owner && <hr className="border-none bg-gray-400 h-[1px]" />}
                  {user.publicMetadata.owner && <MenuItem name="Users" link="/users" icon="users" size="27" alt="users-icon" />}
                  {user.publicMetadata.owner && <MenuItem name="Trades" link="/trades" icon="trades" size="30" alt="trades-icon" />}
                  {user.publicMetadata.owner && <MenuItem name="Settings" link="/settings" icon="settings" size="25" alt="settings-icon" />}
                  {user.publicMetadata.owner && <MenuItem name="Pairs" link="/pairs" icon="pairs" size="25" alt="pairs-icon" />}
                  {user.publicMetadata.owner && <MenuItem name="Companies" link="/companies" icon="company" size="25" alt="companies-icon" />}
                </div>
              </div>
            )}
            <div className="flex-grow overflow-auto">
              <div>{children}</div>
            </div>
          </div>
          */

/*


          import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { UserButton } from "@clerk/nextjs";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import MainMenuServer from "@/components/MainMenu/MainMenuServer";
import TopBar from "@/components/TopBar/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-gray-950 text-white py-[60px]`}>
          <TopBar />
          {children}
          <MainMenuServer />
          <ToastContainer position="bottom-right" autoClose={8000} hideProgressBar={false} newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss draggable={false} pauseOnHover theme="dark" />
        </body>
      </html>
    </ClerkProvider>
  );
}


*/
