import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import Head from "next/head";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          {/* Εδώ προσθέτεις το script */}
          <script src="https://app.livechatai.com/embed.js" data-id="cm00vudtf0001ltkpx3o9fyr4" async defer></script>
        </Head>
        <body className={`${inter.className} bg-gray-950 text-white overflow-x-clip`}>
          {children}
          <ToastContainer position="bottom-right" autoClose={8000} hideProgressBar={false} newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss draggable={false} pauseOnHover theme="dark" />
        </body>
      </html>
    </ClerkProvider>
  );
}
